### ISSUE TITLE
How run release version 0.0.1

### ISSUE THREAD

**Issue by gandalf12345** [MysteriumNetwork/mysterion#151]
How run release version 0.0.1?

**Comment by shroomist** [comment]
hello, some of the binary dependencies are not included for now, so building from source is not possible just yet. We're hoping to release this for public in the near future, stay tuned.

**Comment by gandalf12345** [comment]
I wait, good luck

**Comment by anonymousReaper** [comment]
looking forward to the release.

**Comment by donce** [comment]
Closing this, since releases are already available as described above.
