### ISSUE TITLE
Support Node.js v10.0.0

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/mysterion#179]
I'm running the latest release of Node.js and NPM

```sh
$ node --version
v10.0.0
$ npm --version
5.6.0
```

And currently on master branch, it's impossible to build by `yarn install`

```sh
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
```

Well, I don't want to downgrade my Node.js packages, is it possible to solve this by some changes to the source code?

**Comment by zyfdegh** [comment]
Solved by 
```
yarn config set ignore-engines true
```
Reference: [Install failed with Node v.10 due to upath@1.0.4 incompatibility](https://github.com/facebook/create-react-app/issues/4367)

**Comment by ignasbernotas** [comment]
Hi, as node v10 isn't marked as LTS I suggest you stick with v8 for now. If we'll see some benefits in switching to v10 we'll update the repo accordingly. Cheers:)

**Comment by zyfdegh** [comment]
Thank you @ignasbernotas
