### ISSUE TITLE
framework execution

### ISSUE THREAD

**Issue by anonymousReaper** [MysteriumNetwork/mysterion#208]
Hi, 

It's a really great idea to have VPN on a decentralized network - p2p. How can we run this through a Command Line Interface on Linux, do you have a wiki documentation on how to execute the framework?

Thank you!

**Comment by Waldz** [comment]
If You're interested in connecting to network or API integration? https://github.com/MysteriumNetwork/node/blob/master/CONTRIBUTING.md#running-client-in-interactive-cli

Node running for 3rd parties, will be announced soon

**Comment by donce** [comment]
You can already use 'node' directly by downloading client and starting it with '--cli' flag: https://github.com/MysteriumNetwork/node/releases
@anonymousReaper if you have any more questions, feel free to re-open issue :)
